### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by amayer5125** [tlee911/errbot-httpcats#4]
Please add a LICENSE file to your repository. This helps users by adding a badge on your project showing how they are allowed to use your project. If you don't have a specific license in mind [choosealicense.com](https://choosealicense.com/) is a good resource to get started.

**Comment by tlee911** [comment]
Thanks!  Added MIT license in https://github.com/tlee911/errbot-httpcats/commit/bce450604c02c8d2fa4328e79f5097b6e149e31a
